Drop x86-mingw32 from rake gem:native build
Runing `rake gem:x86-mingw32` currently fails with:

```
linking shared-object re2.so
/usr/bin/i686-w64-mingw32-ld: /tmp/re2/ports/i386-mingw32/i686-w64-mingw32/abseil/20230125.3/lib/libabsl_symbolize.a(symbolize.cc.obj):symbolize.cc:(.text+0x106): undefined reference to `_imp__SymFromAddr@20'
collect2: error: ld returned 1 exit status
```

`SymFromAddr` comes from the Windows Debug Help Library. This linker
error could be fixed by adding `-ldbghelp`, but since this native gem
is not a well-tested package drop it for now.