Fix rb_gc_location definition for Ruby < 2.7
Define rb_gc_location as the identity function for Ruby < 2.7 so that
the code it generates is valid otherwise we get syntax errors like the
following:

    ../../../../ext/re2/re2.cc: In function 'void re2_matchdata_update_references(void*)':
    ../../../../ext/re2/re2.cc:142:46: error: expected primary-expression before ';' token
      142 |   self->regexp = rb_gc_location(self->regexp);